In [3]:
import pygame
pygame.init()

screen = pygame.display.set_mode([500,500])

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
            
    screen.fill((255,255,255))
    
    pygame.draw.circle(screen, (0,0,255), (20,250), 75)
    
    pygame.display.flip()
    
pygame.quit()


In [1]:
# First game attempt
import pygame
import random

from pygame.locals import(RLEACCEL, K_UP, K_DOWN, K_LEFT, K_RIGHT, K_ESCAPE, KEYDOWN, QUIT,)

screen_width = 800
screen_height = 600

class Player(pygame.sprite.Sprite):
    def __init__(self):
        super(Player, self).__init__()
        self.surf = pygame.transform.scale(pygame.image.load("C:\\Users\\nc4lab\\Documents\\AW_Code\\rat.png").convert(), (20, 20)) 
        self.surf.set_colorkey((255,255,255), RLEACCEL)
        self.rect = self.surf.get_rect()
        
    def update(self, pressed_keys):
        if pressed_keys[K_UP]:
            self.rect.move_ip(0, -1)
        if pressed_keys[K_DOWN]:
            self.rect.move_ip(0, 1)
        if pressed_keys[K_LEFT]:
            self.rect.move_ip(-1, 0)
        if pressed_keys[K_RIGHT]:
            self.rect.move_ip(1, 0)
            
        if self.rect.left < 0:
            self.rect.left = 0
        if self.rect.right > screen_width:
            self.rect.right = screen_width
        if self.rect.top <= 0:
            self.rect.top = 0
        if self.rect.bottom >= screen_height:
            self.rect.bottom = screen_height
            
class Enemy(pygame.sprite.Sprite):
    def __init__(self):
        super(Enemy, self).__init__()
        self.surf = pygame.Surface((20, 10))
        self.surf.fill((255, 255, 255))
        self.rect = self.surf.get_rect(
            center=(random.randint(screen_width + 20, screen_width + 100),
                random.randint(0, screen_height),))
        self.speed = 1
        
    def update(self):
        self.rect.move_ip(-self.speed, 0)
        if self.rect.right < 0:
            self.kill()
pygame.init()

screen = pygame.display.set_mode((screen_width, screen_height))


ADDENEMY = pygame.USEREVENT + 1
pygame.time.set_timer(ADDENEMY, 250)

player = Player()

enemies = pygame.sprite.Group()
all_sprites = pygame.sprite.Group()
all_sprites.add(player)

running = True

while running:
    for event in pygame.event.get():
        if event.type == KEYDOWN:
            if event.key == K_ESCAPE:
                running = False
        elif event.type == QUIT:
            running = False

        elif event.type == ADDENEMY:
            new_enemy = Enemy()
            enemies.add(new_enemy)
            all_sprites.add(new_enemy)
            
    pressed_keys = pygame.key.get_pressed()
    
    player.update(pressed_keys)
    
    enemies.update()
    
    screen.fill((0,0,0))

    for entity in all_sprites:
        screen.blit(entity.surf, entity.rect)
        
    if pygame.sprite.spritecollideany(player, enemies):
        player.kill()
        running = False

    pygame.display.flip()
    
pygame.quit()

pygame 2.0.1 (SDL 2.0.14, Python 3.8.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [20]:
#Rat moving simulation
import pygame
import sys
import math
import numpy as np

from pygame.locals import(RLEACCEL, K_UP, K_DOWN, K_LEFT, K_RIGHT, K_ESCAPE, KEYDOWN, QUIT, K_SPACE)

vel = 0

class Rat(pygame.sprite.Sprite):
    def __init__(self):
        super(Rat, self).__init__()
        self.surf = pygame.transform.scale(pygame.image.load(r"C:\Users\\Andy Wang\\Documents\\Code\\rat.png").convert(), (20, 20)) 
        self.surf.set_colorkey((255,255,255), RLEACCEL)
        self.rect = self.surf.get_rect()
        
    def update(self, pressed_keys):
        if pressed_keys[K_UP]:
            vel = 1
        if pressed_keys[K_DOWN]:
            vel = -1
#         if pressed_keys[K_LEFT]:
#             self.rect.move_ip(-1, 0)
#         if pressed_keys[K_RIGHT]:
#             self.rect.move_ip(1, 0)
            
#         if self.rect.left < 0:
#             self.rect.left = 0
#         if self.rect.right > screen_width:
#             self.rect.right = screen_width
#         if self.rect.top <= 0:
#             self.rect.top = 0
#         if self.rect.bottom >= screen_height:
#             self.rect.bottom = screen_height

pygame.init()        
screen_width = 1000
screen_height = 1000
screen = pygame.display.set_mode((screen_width, screen_height))
clock = pygame.time.Clock()
rat = Rat()

img = pygame.transform.scale(pygame.image.load("C:\\Users\\Andy Wang\\Documents\\Code\\rat.png").convert(), (50, 50))
angle = 0
c_list = []
x, y = 300, 300
pressed_keys = pygame.key.get_pressed()


def draw_line(surface, color, pos1, pos2):
    pygame.draw.line(surface, color, pos1, pos2)


running = True
while running:
    screen.fill((122,122,122))
    pressed_keys = pygame.key.get_pressed()
    x -= math.sin(angle*math.pi/180)*vel
    y += math.cos(angle*math.pi/180)*vel 
    angle += 3
    ticks = pygame.time.get_ticks()

    if [x,y] not in c_list:
        c_list.append([x,y])
        round_list = np.around(c_list, decimals = 5)
        hope = np.where(round_list == [300, 300])
        print(hope[0])
    for event in pygame.event.get():
        if event.type == KEYDOWN:
            if event.key == K_ESCAPE:
                running = False
            if event.key == K_UP:
                vel = 5
            if event.key == K_DOWN:
                vel = -5
            if event.key == K_SPACE:
                vel = 0
        elif event.type == QUIT:
            running = False

               
    for i in range(len(c_list)-1):
        draw_line(screen,(0,0,0),c_list[i],c_list[i+1])
    clock.tick(40)
  
    img_copy = pygame.transform.rotate(img, -angle)
    screen.blit(img_copy,(x-int(img_copy.get_width()/2),y-int(img_copy.get_width()/2)))
    pygame.display.flip()
    
pygame.quit()

[0 0]
[0 0]
[0 0]
[0 0]
[0 0]
[0 0]
[0 0]
[0 0]
[0 0]
[0 0]
[0 0]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]
[ 0  0 11]

In [45]:
def nearly_equal(a,b,sig_fig=5):
    if a == b:
        return True
    else:
        return False

a = c_list
b = 300.0000, 300
nearly_equal(a, b,sig_fig=5)

False